language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
before_script: travis_wait 45 ./mvnw install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true
script: ./mvnw install -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
before_install:
 - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: rscruz-calculadora-custo
notifications:
    slack: $HEROKU_API_KEY